site_name: LandOfSignals Wiki
theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.expand
    - navigation.footer
    - toc.follow
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
extra:
  annotate:
    json: [.s2]
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/ykAqHKYjVM
    - icon: fontawesome/brands/github
      link: https://github.com/LandOfRails/LandOfSignals

