# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: LandOfSignals Build Pipeline

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**' # FIXME remove before finishing issue

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: # FIXME rollback changes to the matrix
        branch: [ 1.12.2-forge ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Install deps
        run: sudo apt install -y pngquant findutils xvfb
      - name: Setup Universal Mod Core (and helpers)
        env:
          BRANCH: ${{ matrix.branch }}
        run: java -jar UMCSetup.jar ${BRANCH} https
      - name: Gradle compile
        run: ./gradlew classes
      - name: Process images
        run: find src/main/resources/assets/landofsignals/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
      - name: Run Data (optionalish)
        run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true
      - name: Gradle build
        run: ./gradlew build
      - name: Download UMC version used for build
        run: |
          umc_link=$(./gradlew showBuildInfo | grep "universalmodcore")
          wget $umc_link -P build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: LandOfSignals ${{matrix.branch}}
          path: |
            build/libs/LandOfSignals-${{matrix.branch}}-*
            build/libs/UniversalModCore-*
