name: Pull Request Checklist
on:
  pull_request_target:
    types: [opened]
  
jobs:
  comment:
    - name: Create or Update Comment
	  uses: peter-evans/create-or-update-comment@v1.4.5
	  with:
	    issue-number: ${{ github.event.pull_request.number }}
		body: |
		  ### A few things you might want to check:
		  - [ ] Compilable in every MC version
		  - [ ] Works on client
		  - [ ] Works on server
		  - [ ] Works with content-packs
		  - [ ] Backwards compatible (Blocks, Tiles)
