name: Pull Request Checklist
on:
  pull_request_target:
    types: [opened]
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Render template
      id: template
      uses: chuhlomin/render-template@v1.2
      with:
        template: .github/workflows/pullrequest.md
    - name: Create or Update Comment
      uses: peter-evans/create-or-update-comment@v1.4.5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ comment.template.outputs.result }}
