name: LandOfSignals Release Pipeline

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [ 1.7.10-forge, 1.10.2-forge, 1.11.2-forge, 1.12.2-forge, 1.14.4-forge, 1.15.2-forge, 1.16.5-forge ]
        include:
          - branch: 1.7.10-forge
            version: 1.7.10
          - branch: 1.10.2-forge
            version: 1.10.2
          - branch: 1.11.2-forge
            version: 1.11.2
          - branch: 1.12.2-forge
            version: 1.12.2
          - branch: 1.14.4-forge
            version: 1.14.4
          - branch: 1.15.2-forge
            version: 1.15.2
          - branch: 1.16.5-forge
            version: 1.16.5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Install deps
        run: sudo apt install -y pngquant findutils xvfb
      - name: Hack Forge Gradle
        run: mkdir -p ~/.gradle/caches/minecraft/; wget 'https://teamopenindustry.cc/maven/hack/ForgeGradleVersion.json' -O ~/.gradle/caches/minecraft/ForgeGradleVersion.json
      - name: Setup Universal Mod Core (and helpers)
        env:
          BRANCH: ${{ matrix.branch }}
        run: ./gradlew umc -D umc.loader=${BRANCH} -D ssh.http=true -Dtarget=release
      - name: Gradle compile
        run: ./gradlew classes
      - name: Process images
        run: find src/main/resources/assets/landofsignals/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
      - name: Run Data (optionalish)
        run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true
      - name: Gradle build
        run: ./gradlew build -Dtarget=release
      - uses: actions/upload-artifact@v2
        with:
          name: LandOfSignals ${{matrix.branch}}
          path: build/libs/LandOfSignals-${{matrix.branch}}-*
      - name: Read CHANGELOG.md file
        id: getchangelog
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ./CHANGELOG.md
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Read SUFFIX file
        id: getsuffix
        run: echo "::set-output name=suffix::$(cat SUFFIX)"
      - name: Rename with suffix
        run: mv -n build/libs/LandOfSignals-${{matrix.branch}}-${{ steps.getversion.outputs.version }}.jar build/libs/LandOfSignals-${{matrix.branch}}-${{ steps.getversion.outputs.version }}${{ steps.getsuffix.outputs.suffix }}.jar
      - name: Upload to CurseForge ${{matrix.branch}}
        uses: MarkenJaden/curseforge-upload@master
        with:
          token: ${{ secrets.LANDOFSIGNALS_UPLOAD }}
          project_id: 434307
          game_endpoint: minecraft
          file_path: build/libs/LandOfSignals-${{matrix.branch}}-${{ steps.getversion.outputs.version }}${{ steps.getsuffix.outputs.suffix }}.jar
          changelog: ${{ steps.getchangelog.outputs.content }}
          changelog_type: markdown
          game_versions: ${{ matrix.version }}
          release_type: beta
          relations: universal-mod-core:requiredDependency