name: Test Pipeline

on: [ workflow_dispatch ]

jobs:
  versioncommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Read SUFFIX file
        id: getsuffix
        run: echo "::set-output name=suffix::$(cat SUFFIX)"
      - name: Replace version number with new version
        run: | 
          sed -i 's/^acl public static final String VERSION.*/acl     public static final String VERSION = "${{ steps.getversion.outputs.version }}";/' /src/main/java/net/landofrails/landofsignals/LandOfSignals.java
          sed -i 's/^acl String version =.*/acl String version = '${{ steps.getversion.outputs.version }}'/' ./build.gradle
      - name: Commit and push changes
        run: |
          git config --global user.name "MarkenJaden"
          git config --global user.email "jjsch1410@gmail.com"
          git add -A
          git commit -m "Updated mod version"
          git push
